/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import images.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

public class Main extends javax.swing.JFrame {

    private int originalBannerWidth;
    private int originalBannerHeight;
    private boolean isDarkMode = false; // Theo dõi chế độ tối/sáng
    int x = 210;    //chieu rong
    int y = 700;    //chieu cao

    /**
     * Creates new form Menu
     */
    public Main() {
        initComponents();
        cardTrangChu.setVisible(true);
        cardTaiKhoan.setVisible(false);
        jplSlideMenu.setSize(210, 600);

    }

    public void openMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 210; i++) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(1);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 210;
        }
    }

    public void closeMenu() {
        jplSlideMenu.setSize(x, y);
        if (x == 210) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 210; i >= 0; i--) {
                            jplSlideMenu.setSize(i, y);
                            Thread.sleep(2);
                        }
                    } catch (Exception e) {
                    }
                }
            }).start();
            x = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplMain = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jplSlideMenu = new javax.swing.JPanel();
        lblTrangChu = new javax.swing.JLabel();
        sp = new javax.swing.JLabel();
        nhanhang = new javax.swing.JLabel();
        sanpham = new javax.swing.JLabel();
        thongke = new javax.swing.JLabel();
        nhanvien = new javax.swing.JLabel();
        khachhang = new javax.swing.JLabel();
        lienheHoTro = new javax.swing.JLabel();
        gioiThieu = new javax.swing.JLabel();
        Dangxuat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblCloseMenu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cardTrangChu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpllMenuBar = new javax.swing.JPanel();
        lblOpenMenu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tenTk = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jplMain1 = new javax.swing.JPanel();
        cardTrangChu1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cardTaiKhoan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jplMain.setBackground(new java.awt.Color(255, 255, 255));
        jplMain.setLayout(new java.awt.CardLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplSlideMenu.setBackground(new java.awt.Color(204, 204, 204));
        jplSlideMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jplSlideMenu.setPreferredSize(new java.awt.Dimension(190, 590));
        jplSlideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangChu.setText("Trang Chủ");
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseExited(evt);
            }
        });
        jplSlideMenu.add(lblTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 30));

        sp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sp.setForeground(new java.awt.Color(255, 255, 255));
        sp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sp.setText("Sản Phẩm");
        sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                spMouseExited(evt);
            }
        });
        jplSlideMenu.add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 30));

        nhanhang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nhanhang.setForeground(new java.awt.Color(255, 255, 255));
        nhanhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nhanhang.setText("Nhận Hàng");
        nhanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nhanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nhanhangMouseExited(evt);
            }
        });
        jplSlideMenu.add(nhanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 210, 30));

        sanpham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sanpham.setForeground(new java.awt.Color(255, 255, 255));
        sanpham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sanpham.setText("Sản Phầm");
        sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sanphamMouseExited(evt);
            }
        });
        jplSlideMenu.add(sanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 30));

        thongke.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        thongke.setForeground(new java.awt.Color(255, 255, 255));
        thongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongke.setText("Thống Ke");
        thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thongkeMouseExited(evt);
            }
        });
        jplSlideMenu.add(thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 210, 30));

        nhanvien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        nhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nhanvien.setText("Nhân Viên");
        nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nhanvienMouseExited(evt);
            }
        });
        jplSlideMenu.add(nhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 30));

        khachhang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        khachhang.setForeground(new java.awt.Color(255, 255, 255));
        khachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        khachhang.setText("Khách Hàng");
        khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                khachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                khachhangMouseExited(evt);
            }
        });
        jplSlideMenu.add(khachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 210, 30));

        lienheHoTro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lienheHoTro.setForeground(new java.awt.Color(255, 255, 255));
        lienheHoTro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lienheHoTro.setText("Liên Hệ Hỗ Trợ");
        lienheHoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lienheHoTroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lienheHoTroMouseExited(evt);
            }
        });
        jplSlideMenu.add(lienheHoTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 210, 30));

        gioiThieu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        gioiThieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gioiThieu.setText("Giới Thiệu");
        gioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gioiThieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gioiThieuMouseExited(evt);
            }
        });
        jplSlideMenu.add(gioiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 210, 30));

        Dangxuat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        Dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dangxuat.setText("Đăng Xuất");
        Dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DangxuatMouseExited(evt);
            }
        });
        jplSlideMenu.add(Dangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 210, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\LE DINH LINH\\Downloads\\logo (1).jpg")); // NOI18N
        jLabel6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel6AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblCloseMenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCloseMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseMenu.setText("X");
        lblCloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 170, Short.MAX_VALUE)
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblCloseMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jplSlideMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 140));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Phiên bản v1.0");
        jplSlideMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 650, 100, 30));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplSlideMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LE DINH LINH\\Downloads\\bannermenu.jpg")); // NOI18N
        jLabel1.setLabelFor(jplSlideMenu);
        jplSlideMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 560));

        jPanel1.add(jplSlideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 0, 700));

        cardTrangChu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("jLabel2");
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout cardTrangChuLayout = new javax.swing.GroupLayout(cardTrangChu);
        cardTrangChu.setLayout(cardTrangChuLayout);
        cardTrangChuLayout.setHorizontalGroup(
            cardTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardTrangChuLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardTrangChuLayout.setVerticalGroup(
            cardTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardTrangChuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(cardTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 950, 700));

        jpllMenuBar.setBackground(new java.awt.Color(255, 255, 255));

        lblOpenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        lblOpenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenMenuMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tài khoản:");

        tenTk.setForeground(new java.awt.Color(255, 0, 0));
        tenTk.setText("ledinhlinh");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 255));
        jLabel7.setText("Phần Mềm Quản Lý Điện Thoại Smart Sap");
        jLabel7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel7AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jpllMenuBarLayout = new javax.swing.GroupLayout(jpllMenuBar);
        jpllMenuBar.setLayout(jpllMenuBarLayout);
        jpllMenuBarLayout.setHorizontalGroup(
            jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpllMenuBarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblOpenMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(tenTk)
                .addGap(71, 71, 71))
        );
        jpllMenuBarLayout.setVerticalGroup(
            jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpllMenuBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpllMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tenTk)
                        .addComponent(jLabel7))
                    .addComponent(lblOpenMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jplMain1.setBackground(new java.awt.Color(255, 255, 255));
        jplMain1.setLayout(new java.awt.CardLayout());

        cardTrangChu1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("TRANG CHỦ");

        javax.swing.GroupLayout cardTrangChu1Layout = new javax.swing.GroupLayout(cardTrangChu1);
        cardTrangChu1.setLayout(cardTrangChu1Layout);
        cardTrangChu1Layout.setHorizontalGroup(
            cardTrangChu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTrangChu1Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel12)
                .addContainerGap(438, Short.MAX_VALUE))
        );
        cardTrangChu1Layout.setVerticalGroup(
            cardTrangChu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTrangChu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        jplMain1.add(cardTrangChu1, "card2");

        cardTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Sản Phẩm");

        javax.swing.GroupLayout cardTaiKhoanLayout = new javax.swing.GroupLayout(cardTaiKhoan);
        cardTaiKhoan.setLayout(cardTaiKhoanLayout);
        cardTaiKhoanLayout.setHorizontalGroup(
            cardTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTaiKhoanLayout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel4)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        cardTaiKhoanLayout.setVerticalGroup(
            cardTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTaiKhoanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap(484, Short.MAX_VALUE))
        );

        jplMain1.add(cardTaiKhoan, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpllMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jplMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpllMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jplMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMenuMouseClicked
        closeMenu();
    }//GEN-LAST:event_lblCloseMenuMouseClicked

    private void lblOpenMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenMenuMouseClicked
        openMenu();
    }//GEN-LAST:event_lblOpenMenuMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jplSlideMenu.setSize(0, y);
        x = 0;
    }//GEN-LAST:event_formWindowOpened

    private void nhanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanhangMouseClicked
        cardTaiKhoan.setVisible(true);
        cardTrangChu.setVisible(false);
    }//GEN-LAST:event_nhanhangMouseClicked

    private void lblTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseClicked

        cardTrangChu.setVisible(true);
        cardTaiKhoan.setVisible(true);
    }//GEN-LAST:event_lblTrangChuMouseClicked

    private void jLabel6AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel6AncestorAdded
        String imagePath = "C:\\Users\\LE DINH LINH\\Downloads\\logo (1).jpg"; // Thay đổi đường dẫn tới ảnh của bạn

        // Tải ảnh từ đường dẫn và tạo ImageIcon
        ImageIcon icon = new ImageIcon(imagePath);

        // Resize ảnh theo kích thước của jLabel6
        Image image = icon.getImage(); // Chuyển đổi ImageIcon sang Image
        Image newImage = image.getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_SMOOTH); // Thay đổi kích thước ảnh
        ImageIcon newIcon = new ImageIcon(newImage); // Chuyển đổi lại thành ImageIcon

        // Đặt biểu tượng (icon) mới cho jLabel6
        jLabel6.setIcon(newIcon);
    }//GEN-LAST:event_jLabel6AncestorAdded

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        String imagePath = "C:\\Users\\LE DINH LINH\\Downloads\\banner.jpg"; // Thay đổi đường dẫn tới ảnh của bạn

        // Tải ảnh từ đường dẫn và tạo ImageIcon
        ImageIcon icon = new ImageIcon(imagePath);

        // Resize ảnh theo kích thước của jLabel6
        Image image = icon.getImage(); // Chuyển đổi ImageIcon sang Image
        Image newImage = image.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH); // Thay đổi kích thước ảnh
        ImageIcon newIcon = new ImageIcon(newImage); // Chuyển đổi lại thành ImageIcon

        // Đặt biểu tượng (icon) mới cho jLabel6
        jLabel2.setIcon(newIcon);
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void lblTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseEntered
        // TODO add your handling code here:
        lblTrangChu.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        lblTrangChu.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_lblTrangChuMouseEntered

    private void lblTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseExited
        lblTrangChu.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        lblTrangChu.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_lblTrangChuMouseExited

    private void spMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMouseEntered
        sp.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        sp.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_spMouseEntered

    private void spMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMouseExited
        sp.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        sp.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_spMouseExited

    private void nhanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanhangMouseEntered
        nhanhang.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        nhanhang.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_nhanhangMouseEntered

    private void nhanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanhangMouseExited
        nhanhang.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        nhanhang.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_nhanhangMouseExited

    private void sanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanphamMouseEntered
        sanpham.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        sanpham.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_sanphamMouseEntered

    private void sanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanphamMouseExited
        sanpham.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        sanpham.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_sanphamMouseExited

    private void nhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanvienMouseEntered
        nhanvien.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        nhanvien.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_nhanvienMouseEntered

    private void nhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanvienMouseExited
        nhanvien.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        nhanvien.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_nhanvienMouseExited

    private void khachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachhangMouseEntered
        khachhang.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        khachhang.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_khachhangMouseEntered

    private void khachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachhangMouseExited
        khachhang.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        khachhang.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_khachhangMouseExited

    private void thongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeMouseEntered
        thongke.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        thongke.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_thongkeMouseEntered

    private void thongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeMouseExited
        thongke.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        thongke.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_thongkeMouseExited

    private void lienheHoTroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienheHoTroMouseEntered
        lienheHoTro.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        lienheHoTro.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_lienheHoTroMouseEntered

    private void gioiThieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gioiThieuMouseExited
        gioiThieu.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        gioiThieu.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_gioiThieuMouseExited

    private void DangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangxuatMouseEntered
        Dangxuat.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        Dangxuat.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_DangxuatMouseEntered

    private void DangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangxuatMouseExited
        Dangxuat.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        Dangxuat.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_DangxuatMouseExited

    private void lienheHoTroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienheHoTroMouseExited
        lienheHoTro.setBackground(null); // Trả lại màu nền mặc định khi rời chuột
        lienheHoTro.setOpaque(false); // Đảm bảo phần tử không hiển thị nền màu
    }//GEN-LAST:event_lienheHoTroMouseExited

    private void gioiThieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gioiThieuMouseEntered
        gioiThieu.setBackground(Color.LIGHT_GRAY); // Thay đổi màu nền thành màu đỏ khi di chuột vào
        gioiThieu.setOpaque(true); // Đảm bảo phần tử hiển thị nền màu
    }//GEN-LAST:event_gioiThieuMouseEntered

    private void jLabel7AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel7AncestorAdded
        // Lấy nội dung của JLabel
        String text = jLabel7.getText();

        // Tạo một Thread mới để chạy hiệu ứng
        new Thread(() -> {
            int delay = 100; // Độ trễ giữa các ký tự (tính bằng mili giây)

            // Hiển thị từng phần của chuỗi một cách chậm rãi
            for (int i = 0; i <= text.length(); i++) {
                final int index = i;
                try {
                    // Thực hiện thay đổi trên EDT (Event Dispatch Thread) để update giao diện
                    SwingUtilities.invokeLater(() -> {
                        jLabel7.setText(text.substring(0, index)); // Hiển thị phần của chuỗi từ 0 đến vị trí index
                    });

                    Thread.sleep(delay); // Tạm dừng để tạo hiệu ứng chậm
                } catch (InterruptedException ex) {
                    System.err.println("Exception: " + ex.getMessage());
                }
            }
        }).start();
    }//GEN-LAST:event_jLabel7AncestorAdded

    private void spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMouseClicked
        cardTrangChu1.setVisible(true);

    }//GEN-LAST:event_spMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dangxuat;
    private javax.swing.JPanel cardTaiKhoan;
    private javax.swing.JPanel cardTrangChu;
    private javax.swing.JPanel cardTrangChu1;
    private javax.swing.JLabel gioiThieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jplMain;
    private javax.swing.JPanel jplMain1;
    private javax.swing.JPanel jplSlideMenu;
    private javax.swing.JPanel jpllMenuBar;
    private javax.swing.JLabel khachhang;
    private javax.swing.JLabel lblCloseMenu;
    private javax.swing.JLabel lblOpenMenu;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JLabel lienheHoTro;
    private javax.swing.JLabel nhanhang;
    private javax.swing.JLabel nhanvien;
    private javax.swing.JLabel sanpham;
    private javax.swing.JLabel sp;
    private javax.swing.JLabel tenTk;
    private javax.swing.JLabel thongke;
    // End of variables declaration//GEN-END:variables
}
